import requests

headers = {
    'authority': 'www.svivaaqm.net',
    'accept': '*/*',
    'accept-language': 'en-US,en;q=0.9,he-IL;q=0.8,he;q=0.7',
    'content-type': 'application/json; charset=UTF-8',
    'dnt': '1',
    'origin': 'https://www.svivaaqm.net',
    'referer': 'https://www.svivaaqm.net/',
    'sec-ch-ua': '" Not A;Brand";v="99", "Chromium";v="101", "Google Chrome";v="101"',
    'sec-ch-ua-mobile': '?0',
    'sec-ch-ua-platform': '"Windows"',
    'sec-fetch-dest': 'empty',
    'sec-fetch-mode': 'cors',
    'sec-fetch-site': 'same-origin',
    'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.67 Safari/537.36',
    'x-requested-with': 'XMLHttpRequest',
}

json_data = {
    'monitorChannelsByStationId': {
        '1': [
            2,
            4,
            3,
            5,
            6,
            10,
            1,
            9,
            8,
            7,
        ],
        '2': [
            1,
            3,
            2,
            5,
            11,
        ],
        '3': [
            1,
            3,
            2,
            4,
            7,
            17,
        ],
        '5': [
            15,
            4,
            1,
            3,
            2,
            6,
        ],
        '6': [
            2,
            4,
            3,
            5,
            14,
            16,
            10,
            9,
            8,
            7,
        ],
        '7': [
            2,
            4,
            3,
            5,
            7,
            13,
            11,
            1,
            10,
        ],
        '11': [
            2,
            4,
            3,
            5,
            12,
            10,
            14,
            1,
            13,
            8,
            7,
        ],
        '13': [
            2,
            4,
            3,
            10,
            12,
            8,
            7,
            6,
            5,
        ],
        '21': [
            1,
            3,
            2,
            4,
            16,
            15,
            9,
            8,
            7,
            6,
        ],
        '24': [
            2,
            4,
            3,
            5,
            8,
            7,
            6,
            10,
        ],
        '26': [
            9,
            4,
            2,
            3,
            1,
            5,
        ],
        '32': [
            2,
            4,
            3,
            5,
            6,
            17,
            10,
            1,
            9,
        ],
        '33': [
            4,
            1,
            3,
            2,
            8,
        ],
        '34': [
            14,
            4,
            1,
            3,
            2,
            5,
        ],
        '36': [
            6,
            2,
            4,
            3,
            5,
            14,
            1,
        ],
        '39': [
            6,
            2,
            4,
            3,
            5,
            7,
            13,
            11,
            1,
            10,
            9,
            8,
        ],
        '46': [
            2,
            4,
            3,
            5,
            12,
            11,
            15,
        ],
        '47': [
            18,
            1,
            3,
            2,
            8,
            6,
            7,
        ],
        '53': [
            7,
            8,
            9,
            17,
            20,
            4,
            3,
            2,
            1,
        ],
        '54': [
            2,
            3,
        ],
        '56': [
            7,
            8,
            6,
            5,
            1,
        ],
        '59': [
            7,
            8,
            6,
            5,
            9,
            1,
        ],
        '60': [
            9,
        ],
        '61': [
            7,
            8,
            6,
            5,
            9,
            1,
            3,
            2,
        ],
        '63': [
            7,
            8,
            6,
            5,
            1,
        ],
        '64': [
            7,
            8,
            6,
            5,
            9,
            1,
            3,
            2,
        ],
        '65': [
            7,
            8,
            6,
            5,
            9,
            1,
            10,
            3,
            2,
        ],
        '69': [
            7,
            8,
            6,
            5,
            10,
            13,
            1,
            11,
            3,
            2,
        ],
        '71': [
            7,
            8,
            6,
            5,
            1,
            3,
            2,
        ],
        '72': [
            7,
            8,
            6,
            5,
            1,
        ],
        '73': [
            7,
            8,
            6,
            5,
            1,
            3,
            2,
        ],
        '74': [
            7,
            8,
            6,
            5,
            1,
            3,
            2,
        ],
        '75': [
            7,
            8,
            6,
            5,
            1,
            3,
            2,
        ],
        '76': [
            7,
            8,
            6,
            5,
            1,
            3,
            2,
        ],
        '78': [
            7,
            8,
            6,
            5,
            1,
            3,
            2,
        ],
        '79': [
            9,
            13,
            3,
            7,
            12,
            4,
            8,
            2,
            6,
            1,
            5,
        ],
        '80': [
            7,
            8,
            6,
            5,
            1,
            3,
            2,
        ],
        '81': [
            7,
            8,
            6,
            5,
            9,
            1,
            10,
        ],
        '82': [
            7,
            8,
            6,
            5,
            12,
            1,
            3,
            2,
        ],
        '84': [
            9,
            3,
            2,
        ],
        '85': [
            7,
            8,
            6,
            5,
            1,
            3,
            2,
        ],
        '86': [
            12,
            10,
            11,
            9,
            13,
            15,
            7,
            1,
            5,
            8,
            4,
            2,
            3,
        ],
        '87': [
            10,
            11,
            9,
            13,
            15,
            17,
            1,
            5,
            8,
            4,
        ],
        '88': [
            12,
            10,
            11,
            9,
            13,
            15,
            17,
            1,
            5,
            8,
            4,
            2,
            3,
        ],
        '90': [
            14,
            15,
            13,
            17,
            1,
        ],
        '92': [
            12,
            13,
            11,
            14,
            19,
            6,
            5,
            3,
            2,
        ],
        '93': [
            8,
            9,
            7,
            4,
            2,
            3,
        ],
        '96': [
            15,
            10,
            11,
            23,
            9,
            12,
            13,
            25,
            1,
            5,
            8,
            4,
            3,
            2,
        ],
        '97': [
            8,
            21,
            22,
            20,
            2,
            3,
            1,
            4,
            5,
        ],
        '98': [
            10,
            11,
            9,
            12,
            1,
            2,
            3,
        ],
        '99': [
            2,
            3,
            4,
            10,
            8,
            1,
            7,
        ],
        '100': [
            2,
            3,
            4,
            1,
            6,
            5,
        ],
        '102': [
            10,
            2,
            3,
            4,
            8,
            1,
            7,
            6,
            5,
        ],
        '104': [
            2,
            3,
            4,
            10,
            8,
            1,
            7,
            6,
            5,
        ],
        '105': [
            2,
            3,
            4,
            10,
            8,
            1,
            7,
            6,
            5,
        ],
        '106': [
            2,
            3,
            4,
            8,
            1,
            7,
            6,
            5,
        ],
        '107': [
            2,
            3,
            4,
            10,
            1,
        ],
        '108': [
            2,
            3,
            4,
            8,
            1,
            7,
            6,
            5,
        ],
        '109': [
            2,
            3,
            4,
            8,
            1,
            6,
            5,
        ],
        '110': [
            2,
            3,
            4,
            8,
            9,
            7,
            6,
            5,
        ],
        '111': [
            2,
            3,
            4,
            1,
            6,
            5,
        ],
        '112': [
            2,
            3,
            4,
            8,
            1,
            7,
            6,
            5,
        ],
        '113': [
            2,
            3,
            4,
            23,
            21,
            8,
            27,
            1,
            7,
            6,
            5,
        ],
        '114': [
            2,
            3,
            4,
            8,
            1,
            7,
            6,
            5,
        ],
        '115': [
            23,
            3,
            5,
            4,
            9,
            11,
            15,
            12,
            2,
            8,
            7,
            6,
        ],
        '116': [
            3,
            5,
            4,
            11,
            2,
            7,
            6,
        ],
        '117': [
            3,
            5,
            4,
            9,
            13,
            11,
            2,
            8,
            7,
            6,
        ],
        '122': [
            15,
            10,
            11,
            9,
            8,
            18,
            12,
            5,
            7,
            4,
            3,
            2,
        ],
        '123': [
            13,
            15,
            2,
            3,
            22,
            9,
            8,
            1,
            7,
            5,
            6,
        ],
        '124': [
            14,
            15,
            2,
            3,
            4,
            9,
            8,
            1,
            7,
            5,
            6,
        ],
        '125': [
            14,
            15,
            2,
            3,
            4,
            9,
            1,
            7,
            5,
            6,
        ],
        '126': [
            14,
            15,
            2,
            3,
            4,
            9,
            8,
            1,
            7,
            5,
            6,
        ],
        '127': [
            14,
            15,
            2,
            3,
            4,
            9,
            8,
            1,
            7,
            5,
            6,
        ],
        '128': [
            14,
            15,
            2,
            4,
            9,
            8,
            1,
            7,
            5,
            6,
        ],
        '129': [
            14,
            15,
            2,
            4,
            9,
            8,
            1,
            7,
            5,
            6,
        ],
        '130': [
            14,
            15,
            2,
            3,
            24,
            9,
            8,
            1,
            7,
            5,
            6,
        ],
        '131': [
            14,
            15,
            2,
            3,
            18,
            9,
            8,
            1,
            7,
            5,
            6,
        ],
        '132': [
            4,
            12,
            13,
            11,
            14,
            2,
            1,
        ],
        '133': [
            4,
            12,
            13,
            11,
            14,
            2,
            1,
        ],
        '134': [
            4,
            12,
            13,
            11,
            14,
            2,
            1,
        ],
        '135': [
            4,
            12,
            13,
            11,
            14,
            2,
            1,
        ],
        '136': [
            11,
            12,
            10,
            30,
            20,
            1,
            4,
            2,
            3,
        ],
        '137': [
            9,
            10,
            8,
            5,
            18,
            11,
            12,
            1,
            4,
            2,
            3,
        ],
        '138': [
            4,
            12,
            13,
            11,
            14,
            2,
            1,
        ],
        '139': [
            4,
            1,
            3,
            2,
            6,
        ],
        '140': [
            9,
            10,
            3,
            2,
        ],
        '154': [
            4,
            1,
            3,
            2,
            6,
        ],
        '158': [
            5,
            6,
            7,
            2,
            4,
            9,
        ],
        '160': [
            16,
            13,
            14,
            2,
            3,
            4,
            9,
            8,
            1,
            7,
            5,
            6,
        ],
        '170': [
            1,
            3,
            2,
            6,
        ],
        '182': [
            3,
            17,
            4,
            19,
            11,
            2,
            10,
            6,
            5,
        ],
        '183': [
            3,
            17,
            4,
            19,
            11,
            2,
            10,
            6,
            5,
        ],
        '184': [
            3,
            18,
            4,
            21,
            11,
            2,
            10,
            6,
            5,
        ],
        '185': [
            1,
            12,
            11,
            10,
            8,
        ],
        '186': [
            1,
            7,
            9,
            12,
            11,
            10,
            8,
        ],
        '187': [
            1,
            12,
            11,
            10,
            8,
        ],
        '188': [
            1,
            12,
            11,
            10,
            8,
        ],
        '189': [
            13,
            4,
            1,
            3,
            2,
            5,
            6,
            22,
        ],
        '193': [
            3,
            4,
            5,
            6,
        ],
        '304': [
            1,
        ],
        '306': [
            14,
            15,
            2,
            3,
            4,
            18,
            9,
            8,
            1,
            7,
            5,
            6,
        ],
        '309': [
            1,
            2,
            4,
            5,
        ],
        '310': [
            2,
            4,
            3,
            1,
        ],
        '321': [
            2,
            3,
            4,
            9,
            17,
            10,
            1,
            6,
            5,
        ],
        '322': [
            8,
            5,
            1,
            4,
            3,
        ],
        '326': [
            9,
            10,
            11,
            8,
            1,
            3,
            2,
        ],
        '328': [
            7,
            5,
            6,
            4,
            9,
            8,
            3,
            1,
            2,
        ],
        '331': [
            3,
            5,
            4,
            1,
            7,
            6,
            11,
            2,
            10,
            9,
            8,
        ],
        '334': [
            3,
            4,
            5,
            6,
        ],
        '337': [
            9,
            1,
            3,
            2,
            16,
            7,
        ],
        '338': [
            3,
            5,
            2,
            6,
            1,
        ],
        '339': [
            9,
            6,
            7,
            8,
            2,
        ],
        '341': [
            4,
            3,
            2,
            1,
        ],
        '345': [
            14,
            1,
            7,
            5,
            4,
            8,
            2,
            9,
            11,
            10,
        ],
        '346': [
            2,
            4,
            3,
            1,
            6,
            5,
        ],
        '348': [
            3,
            4,
            5,
            6,
            1,
            2,
        ],
        '349': [
            7,
            3,
            4,
            2,
            1,
        ],
        '353': [
            9,
            6,
        ],
        '357': [
            8,
            1,
            2,
            3,
            4,
            5,
            13,
            6,
            15,
            14,
        ],
        '365': [
            4,
            5,
            6,
            2,
            8,
            1,
        ],
        '367': [
            7,
            8,
            6,
            5,
            14,
            15,
            12,
            1,
            10,
            3,
            2,
        ],
        '371': [
            9,
            1,
            2,
            3,
            4,
            5,
            6,
            7,
        ],
        '375': [
            1,
            3,
            2,
            4,
            7,
            16,
            18,
            20,
            13,
            19,
        ],
        '377': [
            7,
            8,
            6,
            5,
            1,
            3,
            2,
        ],
        '378': [
            7,
            8,
            6,
            5,
            9,
            12,
            1,
            10,
            3,
            2,
        ],
        '379': [
            1,
        ],
        '380': [
            8,
            9,
            7,
            14,
            6,
            2,
            3,
        ],
        '382': [
            13,
            5,
            6,
            4,
            7,
            10,
            8,
        ],
        '383': [
            25,
            2,
            4,
            3,
            5,
            12,
            9,
            7,
            6,
        ],
        '384': [
            3,
            4,
            5,
            6,
            1,
            2,
        ],
        '386': [
            3,
            4,
            5,
            6,
            1,
            2,
        ],
        '387': [
            1,
            2,
            3,
            9,
            5,
            4,
        ],
        '391': [
            5,
            4,
            1,
            2,
            3,
            9,
        ],
        '393': [
            5,
            4,
            1,
            2,
            3,
        ],
        '397': [
            10,
            1,
            3,
            2,
            4,
            6,
        ],
        '400': [
            1,
            2,
            3,
            4,
            5,
        ],
        '401': [
            1,
        ],
        '405': [
            3,
            4,
            2,
            5,
        ],
        '406': [
            4,
            5,
            3,
            6,
            1,
        ],
        '414': [
            4,
            1,
            3,
            2,
            6,
            5,
        ],
        '416': [
            1,
            2,
        ],
        '417': [
            2,
            4,
            3,
            1,
            5,
            6,
        ],
        '423': [
            5,
            7,
            6,
            2,
            8,
        ],
        '426': [
            1,
            6,
            2,
            3,
        ],
        '427': [
            2,
            1,
            3,
        ],
        '428': [
            11,
            2,
            3,
            4,
            10,
            9,
            1,
            6,
            5,
        ],
        '452': [
            13,
            2,
            3,
            4,
            12,
            1,
            6,
            5,
        ],
        '453': [
            14,
            2,
            3,
            4,
            12,
            11,
            1,
            7,
            6,
            5,
        ],
        '454': [
            2,
            3,
            4,
            9,
            20,
            18,
            14,
            8,
            1,
            7,
            6,
            5,
        ],
        '455': [
            1,
            11,
            12,
            10,
            13,
        ],
        '456': [
            1,
            8,
            9,
            7,
            10,
        ],
        '458': [
            10,
            1,
            2,
            3,
            8,
        ],
        '465': [
            1,
            5,
            4,
        ],
        '467': [
            1,
        ],
        '468': [
            3,
            4,
            5,
            1,
            6,
            2,
        ],
        '469': [
            3,
            4,
            5,
            1,
            6,
            2,
            8,
            7,
        ],
        '472': [
            11,
            2,
            3,
            4,
            10,
            9,
            1,
            6,
            5,
        ],
        '498': [
            1,
            7,
            8,
            6,
            9,
        ],
        '499': [
            3,
            12,
            13,
            11,
            9,
            18,
            8,
            17,
            1,
            2,
        ],
        '501': [
            1,
            2,
            3,
            5,
        ],
        '505': [
            6,
        ],
        '509': [
            4,
            1,
            2,
            3,
            11,
        ],
        '510': [
            1,
            2,
            3,
            7,
            4,
        ],
        '511': [
            9,
            2,
            4,
            3,
            1,
            6,
            5,
        ],
        '513': [
            4,
            6,
            5,
            2,
            1,
            3,
        ],
        '517': [
            1,
        ],
        '528': [
            2,
            4,
            3,
            1,
        ],
        '530': [
            3,
            1,
            8,
            7,
        ],
        '531': [
            1,
            2,
            3,
            4,
            6,
            5,
            9,
            8,
        ],
        '532': [
            1,
            2,
            3,
            4,
            6,
            5,
        ],
        '533': [
            4,
            1,
            2,
            3,
        ],
        '535': [
            2,
            1,
            3,
        ],
        '536': [
            1,
        ],
        '537': [
            3,
            2,
            1,
            5,
            4,
        ],
        '538': [
            3,
            2,
            1,
        ],
        '539': [
            7,
            8,
            6,
            5,
            1,
        ],
    },
    'reportName': 'multi Station report',
    'startDateAbsolute': '25/05/2022 20:01',
    'endDateAbsolute': '25/05/2022 21:00',
    'startDate': '25/05/2022 20:01',
    'endDate': '25/05/2022 21:00',
    'reportType': 'Average',
    'fromTb': 60,
    'toTb': 60,
    'monitorChannelsByStationId[0].Key': '1',
    'monitorChannelsByStationId[0].Value': [
        2,
        4,
        3,
        5,
        6,
        10,
        1,
        9,
        8,
        7,
    ],
    'monitorChannelsByStationId[1].Key': '2',
    'monitorChannelsByStationId[1].Value': [
        1,
        3,
        2,
        5,
        11,
    ],
    'monitorChannelsByStationId[2].Key': '3',
    'monitorChannelsByStationId[2].Value': [
        1,
        3,
        2,
        4,
        7,
        17,
    ],
    'monitorChannelsByStationId[3].Key': '5',
    'monitorChannelsByStationId[3].Value': [
        15,
        4,
        1,
        3,
        2,
        6,
    ],
    'monitorChannelsByStationId[4].Key': '6',
    'monitorChannelsByStationId[4].Value': [
        2,
        4,
        3,
        5,
        14,
        16,
        10,
        9,
        8,
        7,
    ],
    'monitorChannelsByStationId[5].Key': '7',
    'monitorChannelsByStationId[5].Value': [
        2,
        4,
        3,
        5,
        7,
        13,
        11,
        1,
        10,
    ],
    'monitorChannelsByStationId[6].Key': '11',
    'monitorChannelsByStationId[6].Value': [
        2,
        4,
        3,
        5,
        12,
        10,
        14,
        1,
        13,
        8,
        7,
    ],
    'monitorChannelsByStationId[7].Key': '13',
    'monitorChannelsByStationId[7].Value': [
        2,
        4,
        3,
        10,
        12,
        8,
        7,
        6,
        5,
    ],
    'monitorChannelsByStationId[8].Key': '21',
    'monitorChannelsByStationId[8].Value': [
        1,
        3,
        2,
        4,
        16,
        15,
        9,
        8,
        7,
        6,
    ],
    'monitorChannelsByStationId[9].Key': '24',
    'monitorChannelsByStationId[9].Value': [
        2,
        4,
        3,
        5,
        8,
        7,
        6,
        10,
    ],
    'monitorChannelsByStationId[10].Key': '26',
    'monitorChannelsByStationId[10].Value': [
        9,
        4,
        2,
        3,
        1,
        5,
    ],
    'monitorChannelsByStationId[11].Key': '32',
    'monitorChannelsByStationId[11].Value': [
        2,
        4,
        3,
        5,
        6,
        17,
        10,
        1,
        9,
    ],
    'monitorChannelsByStationId[12].Key': '33',
    'monitorChannelsByStationId[12].Value': [
        4,
        1,
        3,
        2,
        8,
    ],
    'monitorChannelsByStationId[13].Key': '34',
    'monitorChannelsByStationId[13].Value': [
        14,
        4,
        1,
        3,
        2,
        5,
    ],
    'monitorChannelsByStationId[14].Key': '36',
    'monitorChannelsByStationId[14].Value': [
        6,
        2,
        4,
        3,
        5,
        14,
        1,
    ],
    'monitorChannelsByStationId[15].Key': '39',
    'monitorChannelsByStationId[15].Value': [
        6,
        2,
        4,
        3,
        5,
        7,
        13,
        11,
        1,
        10,
        9,
        8,
    ],
    'monitorChannelsByStationId[16].Key': '46',
    'monitorChannelsByStationId[16].Value': [
        2,
        4,
        3,
        5,
        12,
        11,
        15,
    ],
    'monitorChannelsByStationId[17].Key': '47',
    'monitorChannelsByStationId[17].Value': [
        18,
        1,
        3,
        2,
        8,
        6,
        7,
    ],
    'monitorChannelsByStationId[18].Key': '53',
    'monitorChannelsByStationId[18].Value': [
        7,
        8,
        9,
        17,
        20,
        4,
        3,
        2,
        1,
    ],
    'monitorChannelsByStationId[19].Key': '54',
    'monitorChannelsByStationId[19].Value': [
        2,
        3,
    ],
    'monitorChannelsByStationId[20].Key': '56',
    'monitorChannelsByStationId[20].Value': [
        7,
        8,
        6,
        5,
        1,
    ],
    'monitorChannelsByStationId[21].Key': '59',
    'monitorChannelsByStationId[21].Value': [
        7,
        8,
        6,
        5,
        9,
        1,
    ],
    'monitorChannelsByStationId[22].Key': '60',
    'monitorChannelsByStationId[22].Value': [
        9,
    ],
    'monitorChannelsByStationId[23].Key': '61',
    'monitorChannelsByStationId[23].Value': [
        7,
        8,
        6,
        5,
        9,
        1,
        3,
        2,
    ],
    'monitorChannelsByStationId[24].Key': '63',
    'monitorChannelsByStationId[24].Value': [
        7,
        8,
        6,
        5,
        1,
    ],
    'monitorChannelsByStationId[25].Key': '64',
    'monitorChannelsByStationId[25].Value': [
        7,
        8,
        6,
        5,
        9,
        1,
        3,
        2,
    ],
    'monitorChannelsByStationId[26].Key': '65',
    'monitorChannelsByStationId[26].Value': [
        7,
        8,
        6,
        5,
        9,
        1,
        10,
        3,
        2,
    ],
    'monitorChannelsByStationId[27].Key': '69',
    'monitorChannelsByStationId[27].Value': [
        7,
        8,
        6,
        5,
        10,
        13,
        1,
        11,
        3,
        2,
    ],
    'monitorChannelsByStationId[28].Key': '71',
    'monitorChannelsByStationId[28].Value': [
        7,
        8,
        6,
        5,
        1,
        3,
        2,
    ],
    'monitorChannelsByStationId[29].Key': '72',
    'monitorChannelsByStationId[29].Value': [
        7,
        8,
        6,
        5,
        1,
    ],
    'monitorChannelsByStationId[30].Key': '73',
    'monitorChannelsByStationId[30].Value': [
        7,
        8,
        6,
        5,
        1,
        3,
        2,
    ],
    'monitorChannelsByStationId[31].Key': '74',
    'monitorChannelsByStationId[31].Value': [
        7,
        8,
        6,
        5,
        1,
        3,
        2,
    ],
    'monitorChannelsByStationId[32].Key': '75',
    'monitorChannelsByStationId[32].Value': [
        7,
        8,
        6,
        5,
        1,
        3,
        2,
    ],
    'monitorChannelsByStationId[33].Key': '76',
    'monitorChannelsByStationId[33].Value': [
        7,
        8,
        6,
        5,
        1,
        3,
        2,
    ],
    'monitorChannelsByStationId[34].Key': '78',
    'monitorChannelsByStationId[34].Value': [
        7,
        8,
        6,
        5,
        1,
        3,
        2,
    ],
    'monitorChannelsByStationId[35].Key': '79',
    'monitorChannelsByStationId[35].Value': [
        9,
        13,
        3,
        7,
        12,
        4,
        8,
        2,
        6,
        1,
        5,
    ],
    'monitorChannelsByStationId[36].Key': '80',
    'monitorChannelsByStationId[36].Value': [
        7,
        8,
        6,
        5,
        1,
        3,
        2,
    ],
    'monitorChannelsByStationId[37].Key': '81',
    'monitorChannelsByStationId[37].Value': [
        7,
        8,
        6,
        5,
        9,
        1,
        10,
    ],
    'monitorChannelsByStationId[38].Key': '82',
    'monitorChannelsByStationId[38].Value': [
        7,
        8,
        6,
        5,
        12,
        1,
        3,
        2,
    ],
    'monitorChannelsByStationId[39].Key': '84',
    'monitorChannelsByStationId[39].Value': [
        9,
        3,
        2,
    ],
    'monitorChannelsByStationId[40].Key': '85',
    'monitorChannelsByStationId[40].Value': [
        7,
        8,
        6,
        5,
        1,
        3,
        2,
    ],
    'monitorChannelsByStationId[41].Key': '86',
    'monitorChannelsByStationId[41].Value': [
        12,
        10,
        11,
        9,
        13,
        15,
        7,
        1,
        5,
        8,
        4,
        2,
        3,
    ],
    'monitorChannelsByStationId[42].Key': '87',
    'monitorChannelsByStationId[42].Value': [
        10,
        11,
        9,
        13,
        15,
        17,
        1,
        5,
        8,
        4,
    ],
    'monitorChannelsByStationId[43].Key': '88',
    'monitorChannelsByStationId[43].Value': [
        12,
        10,
        11,
        9,
        13,
        15,
        17,
        1,
        5,
        8,
        4,
        2,
        3,
    ],
    'monitorChannelsByStationId[44].Key': '90',
    'monitorChannelsByStationId[44].Value': [
        14,
        15,
        13,
        17,
        1,
    ],
    'monitorChannelsByStationId[45].Key': '92',
    'monitorChannelsByStationId[45].Value': [
        12,
        13,
        11,
        14,
        19,
        6,
        5,
        3,
        2,
    ],
    'monitorChannelsByStationId[46].Key': '93',
    'monitorChannelsByStationId[46].Value': [
        8,
        9,
        7,
        4,
        2,
        3,
    ],
    'monitorChannelsByStationId[47].Key': '96',
    'monitorChannelsByStationId[47].Value': [
        15,
        10,
        11,
        23,
        9,
        12,
        13,
        25,
        1,
        5,
        8,
        4,
        3,
        2,
    ],
    'monitorChannelsByStationId[48].Key': '97',
    'monitorChannelsByStationId[48].Value': [
        8,
        21,
        22,
        20,
        2,
        3,
        1,
        4,
        5,
    ],
    'monitorChannelsByStationId[49].Key': '98',
    'monitorChannelsByStationId[49].Value': [
        10,
        11,
        9,
        12,
        1,
        2,
        3,
    ],
    'monitorChannelsByStationId[50].Key': '99',
    'monitorChannelsByStationId[50].Value': [
        2,
        3,
        4,
        10,
        8,
        1,
        7,
    ],
    'monitorChannelsByStationId[51].Key': '100',
    'monitorChannelsByStationId[51].Value': [
        2,
        3,
        4,
        1,
        6,
        5,
    ],
    'monitorChannelsByStationId[52].Key': '102',
    'monitorChannelsByStationId[52].Value': [
        10,
        2,
        3,
        4,
        8,
        1,
        7,
        6,
        5,
    ],
    'monitorChannelsByStationId[53].Key': '104',
    'monitorChannelsByStationId[53].Value': [
        2,
        3,
        4,
        10,
        8,
        1,
        7,
        6,
        5,
    ],
    'monitorChannelsByStationId[54].Key': '105',
    'monitorChannelsByStationId[54].Value': [
        2,
        3,
        4,
        10,
        8,
        1,
        7,
        6,
        5,
    ],
    'monitorChannelsByStationId[55].Key': '106',
    'monitorChannelsByStationId[55].Value': [
        2,
        3,
        4,
        8,
        1,
        7,
        6,
        5,
    ],
    'monitorChannelsByStationId[56].Key': '107',
    'monitorChannelsByStationId[56].Value': [
        2,
        3,
        4,
        10,
        1,
    ],
    'monitorChannelsByStationId[57].Key': '108',
    'monitorChannelsByStationId[57].Value': [
        2,
        3,
        4,
        8,
        1,
        7,
        6,
        5,
    ],
    'monitorChannelsByStationId[58].Key': '109',
    'monitorChannelsByStationId[58].Value': [
        2,
        3,
        4,
        8,
        1,
        6,
        5,
    ],
    'monitorChannelsByStationId[59].Key': '110',
    'monitorChannelsByStationId[59].Value': [
        2,
        3,
        4,
        8,
        9,
        7,
        6,
        5,
    ],
    'monitorChannelsByStationId[60].Key': '111',
    'monitorChannelsByStationId[60].Value': [
        2,
        3,
        4,
        1,
        6,
        5,
    ],
    'monitorChannelsByStationId[61].Key': '112',
    'monitorChannelsByStationId[61].Value': [
        2,
        3,
        4,
        8,
        1,
        7,
        6,
        5,
    ],
    'monitorChannelsByStationId[62].Key': '113',
    'monitorChannelsByStationId[62].Value': [
        2,
        3,
        4,
        23,
        21,
        8,
        27,
        1,
        7,
        6,
        5,
    ],
    'monitorChannelsByStationId[63].Key': '114',
    'monitorChannelsByStationId[63].Value': [
        2,
        3,
        4,
        8,
        1,
        7,
        6,
        5,
    ],
    'monitorChannelsByStationId[64].Key': '115',
    'monitorChannelsByStationId[64].Value': [
        23,
        3,
        5,
        4,
        9,
        11,
        15,
        12,
        2,
        8,
        7,
        6,
    ],
    'monitorChannelsByStationId[65].Key': '116',
    'monitorChannelsByStationId[65].Value': [
        3,
        5,
        4,
        11,
        2,
        7,
        6,
    ],
    'monitorChannelsByStationId[66].Key': '117',
    'monitorChannelsByStationId[66].Value': [
        3,
        5,
        4,
        9,
        13,
        11,
        2,
        8,
        7,
        6,
    ],
    'monitorChannelsByStationId[67].Key': '122',
    'monitorChannelsByStationId[67].Value': [
        15,
        10,
        11,
        9,
        8,
        18,
        12,
        5,
        7,
        4,
        3,
        2,
    ],
    'monitorChannelsByStationId[68].Key': '123',
    'monitorChannelsByStationId[68].Value': [
        13,
        15,
        2,
        3,
        22,
        9,
        8,
        1,
        7,
        5,
        6,
    ],
    'monitorChannelsByStationId[69].Key': '124',
    'monitorChannelsByStationId[69].Value': [
        14,
        15,
        2,
        3,
        4,
        9,
        8,
        1,
        7,
        5,
        6,
    ],
    'monitorChannelsByStationId[70].Key': '125',
    'monitorChannelsByStationId[70].Value': [
        14,
        15,
        2,
        3,
        4,
        9,
        1,
        7,
        5,
        6,
    ],
    'monitorChannelsByStationId[71].Key': '126',
    'monitorChannelsByStationId[71].Value': [
        14,
        15,
        2,
        3,
        4,
        9,
        8,
        1,
        7,
        5,
        6,
    ],
    'monitorChannelsByStationId[72].Key': '127',
    'monitorChannelsByStationId[72].Value': [
        14,
        15,
        2,
        3,
        4,
        9,
        8,
        1,
        7,
        5,
        6,
    ],
    'monitorChannelsByStationId[73].Key': '128',
    'monitorChannelsByStationId[73].Value': [
        14,
        15,
        2,
        4,
        9,
        8,
        1,
        7,
        5,
        6,
    ],
    'monitorChannelsByStationId[74].Key': '129',
    'monitorChannelsByStationId[74].Value': [
        14,
        15,
        2,
        4,
        9,
        8,
        1,
        7,
        5,
        6,
    ],
    'monitorChannelsByStationId[75].Key': '130',
    'monitorChannelsByStationId[75].Value': [
        14,
        15,
        2,
        3,
        24,
        9,
        8,
        1,
        7,
        5,
        6,
    ],
    'monitorChannelsByStationId[76].Key': '131',
    'monitorChannelsByStationId[76].Value': [
        14,
        15,
        2,
        3,
        18,
        9,
        8,
        1,
        7,
        5,
        6,
    ],
    'monitorChannelsByStationId[77].Key': '132',
    'monitorChannelsByStationId[77].Value': [
        4,
        12,
        13,
        11,
        14,
        2,
        1,
    ],
    'monitorChannelsByStationId[78].Key': '133',
    'monitorChannelsByStationId[78].Value': [
        4,
        12,
        13,
        11,
        14,
        2,
        1,
    ],
    'monitorChannelsByStationId[79].Key': '134',
    'monitorChannelsByStationId[79].Value': [
        4,
        12,
        13,
        11,
        14,
        2,
        1,
    ],
    'monitorChannelsByStationId[80].Key': '135',
    'monitorChannelsByStationId[80].Value': [
        4,
        12,
        13,
        11,
        14,
        2,
        1,
    ],
    'monitorChannelsByStationId[81].Key': '136',
    'monitorChannelsByStationId[81].Value': [
        11,
        12,
        10,
        30,
        20,
        1,
        4,
        2,
        3,
    ],
    'monitorChannelsByStationId[82].Key': '137',
    'monitorChannelsByStationId[82].Value': [
        9,
        10,
        8,
        5,
        18,
        11,
        12,
        1,
        4,
        2,
        3,
    ],
    'monitorChannelsByStationId[83].Key': '138',
    'monitorChannelsByStationId[83].Value': [
        4,
        12,
        13,
        11,
        14,
        2,
        1,
    ],
    'monitorChannelsByStationId[84].Key': '139',
    'monitorChannelsByStationId[84].Value': [
        4,
        1,
        3,
        2,
        6,
    ],
    'monitorChannelsByStationId[85].Key': '140',
    'monitorChannelsByStationId[85].Value': [
        9,
        10,
        3,
        2,
    ],
    'monitorChannelsByStationId[86].Key': '154',
    'monitorChannelsByStationId[86].Value': [
        4,
        1,
        3,
        2,
        6,
    ],
    'monitorChannelsByStationId[87].Key': '158',
    'monitorChannelsByStationId[87].Value': [
        5,
        6,
        7,
        2,
        4,
        9,
    ],
    'monitorChannelsByStationId[88].Key': '160',
    'monitorChannelsByStationId[88].Value': [
        16,
        13,
        14,
        2,
        3,
        4,
        9,
        8,
        1,
        7,
        5,
        6,
    ],
    'monitorChannelsByStationId[89].Key': '170',
    'monitorChannelsByStationId[89].Value': [
        1,
        3,
        2,
        6,
    ],
    'monitorChannelsByStationId[90].Key': '182',
    'monitorChannelsByStationId[90].Value': [
        3,
        17,
        4,
        19,
        11,
        2,
        10,
        6,
        5,
    ],
    'monitorChannelsByStationId[91].Key': '183',
    'monitorChannelsByStationId[91].Value': [
        3,
        17,
        4,
        19,
        11,
        2,
        10,
        6,
        5,
    ],
    'monitorChannelsByStationId[92].Key': '184',
    'monitorChannelsByStationId[92].Value': [
        3,
        18,
        4,
        21,
        11,
        2,
        10,
        6,
        5,
    ],
    'monitorChannelsByStationId[93].Key': '185',
    'monitorChannelsByStationId[93].Value': [
        1,
        12,
        11,
        10,
        8,
    ],
    'monitorChannelsByStationId[94].Key': '186',
    'monitorChannelsByStationId[94].Value': [
        1,
        7,
        9,
        12,
        11,
        10,
        8,
    ],
    'monitorChannelsByStationId[95].Key': '187',
    'monitorChannelsByStationId[95].Value': [
        1,
        12,
        11,
        10,
        8,
    ],
    'monitorChannelsByStationId[96].Key': '188',
    'monitorChannelsByStationId[96].Value': [
        1,
        12,
        11,
        10,
        8,
    ],
    'monitorChannelsByStationId[97].Key': '189',
    'monitorChannelsByStationId[97].Value': [
        13,
        4,
        1,
        3,
        2,
        5,
        6,
        22,
    ],
    'monitorChannelsByStationId[98].Key': '193',
    'monitorChannelsByStationId[98].Value': [
        3,
        4,
        5,
        6,
    ],
    'monitorChannelsByStationId[99].Key': '304',
    'monitorChannelsByStationId[99].Value': [
        1,
    ],
    'monitorChannelsByStationId[100].Key': '306',
    'monitorChannelsByStationId[100].Value': [
        14,
        15,
        2,
        3,
        4,
        18,
        9,
        8,
        1,
        7,
        5,
        6,
    ],
    'monitorChannelsByStationId[101].Key': '309',
    'monitorChannelsByStationId[101].Value': [
        1,
        2,
        4,
        5,
    ],
    'monitorChannelsByStationId[102].Key': '310',
    'monitorChannelsByStationId[102].Value': [
        2,
        4,
        3,
        1,
    ],
    'monitorChannelsByStationId[103].Key': '321',
    'monitorChannelsByStationId[103].Value': [
        2,
        3,
        4,
        9,
        17,
        10,
        1,
        6,
        5,
    ],
    'monitorChannelsByStationId[104].Key': '322',
    'monitorChannelsByStationId[104].Value': [
        8,
        5,
        1,
        4,
        3,
    ],
    'monitorChannelsByStationId[105].Key': '326',
    'monitorChannelsByStationId[105].Value': [
        9,
        10,
        11,
        8,
        1,
        3,
        2,
    ],
    'monitorChannelsByStationId[106].Key': '328',
    'monitorChannelsByStationId[106].Value': [
        7,
        5,
        6,
        4,
        9,
        8,
        3,
        1,
        2,
    ],
    'monitorChannelsByStationId[107].Key': '331',
    'monitorChannelsByStationId[107].Value': [
        3,
        5,
        4,
        1,
        7,
        6,
        11,
        2,
        10,
        9,
        8,
    ],
    'monitorChannelsByStationId[108].Key': '334',
    'monitorChannelsByStationId[108].Value': [
        3,
        4,
        5,
        6,
    ],
    'monitorChannelsByStationId[109].Key': '337',
    'monitorChannelsByStationId[109].Value': [
        9,
        1,
        3,
        2,
        16,
        7,
    ],
    'monitorChannelsByStationId[110].Key': '338',
    'monitorChannelsByStationId[110].Value': [
        3,
        5,
        2,
        6,
        1,
    ],
    'monitorChannelsByStationId[111].Key': '339',
    'monitorChannelsByStationId[111].Value': [
        9,
        6,
        7,
        8,
        2,
    ],
    'monitorChannelsByStationId[112].Key': '341',
    'monitorChannelsByStationId[112].Value': [
        4,
        3,
        2,
        1,
    ],
    'monitorChannelsByStationId[113].Key': '345',
    'monitorChannelsByStationId[113].Value': [
        14,
        1,
        7,
        5,
        4,
        8,
        2,
        9,
        11,
        10,
    ],
    'monitorChannelsByStationId[114].Key': '346',
    'monitorChannelsByStationId[114].Value': [
        2,
        4,
        3,
        1,
        6,
        5,
    ],
    'monitorChannelsByStationId[115].Key': '348',
    'monitorChannelsByStationId[115].Value': [
        3,
        4,
        5,
        6,
        1,
        2,
    ],
    'monitorChannelsByStationId[116].Key': '349',
    'monitorChannelsByStationId[116].Value': [
        7,
        3,
        4,
        2,
        1,
    ],
    'monitorChannelsByStationId[117].Key': '353',
    'monitorChannelsByStationId[117].Value': [
        9,
        6,
    ],
    'monitorChannelsByStationId[118].Key': '357',
    'monitorChannelsByStationId[118].Value': [
        8,
        1,
        2,
        3,
        4,
        5,
        13,
        6,
        15,
        14,
    ],
    'monitorChannelsByStationId[119].Key': '365',
    'monitorChannelsByStationId[119].Value': [
        4,
        5,
        6,
        2,
        8,
        1,
    ],
    'monitorChannelsByStationId[120].Key': '367',
    'monitorChannelsByStationId[120].Value': [
        7,
        8,
        6,
        5,
        14,
        15,
        12,
        1,
        10,
        3,
        2,
    ],
    'monitorChannelsByStationId[121].Key': '371',
    'monitorChannelsByStationId[121].Value': [
        9,
        1,
        2,
        3,
        4,
        5,
        6,
        7,
    ],
    'monitorChannelsByStationId[122].Key': '375',
    'monitorChannelsByStationId[122].Value': [
        1,
        3,
        2,
        4,
        7,
        16,
        18,
        20,
        13,
        19,
    ],
    'monitorChannelsByStationId[123].Key': '377',
    'monitorChannelsByStationId[123].Value': [
        7,
        8,
        6,
        5,
        1,
        3,
        2,
    ],
    'monitorChannelsByStationId[124].Key': '378',
    'monitorChannelsByStationId[124].Value': [
        7,
        8,
        6,
        5,
        9,
        12,
        1,
        10,
        3,
        2,
    ],
    'monitorChannelsByStationId[125].Key': '379',
    'monitorChannelsByStationId[125].Value': [
        1,
    ],
    'monitorChannelsByStationId[126].Key': '380',
    'monitorChannelsByStationId[126].Value': [
        8,
        9,
        7,
        14,
        6,
        2,
        3,
    ],
    'monitorChannelsByStationId[127].Key': '382',
    'monitorChannelsByStationId[127].Value': [
        13,
        5,
        6,
        4,
        7,
        10,
        8,
    ],
    'monitorChannelsByStationId[128].Key': '383',
    'monitorChannelsByStationId[128].Value': [
        25,
        2,
        4,
        3,
        5,
        12,
        9,
        7,
        6,
    ],
    'monitorChannelsByStationId[129].Key': '384',
    'monitorChannelsByStationId[129].Value': [
        3,
        4,
        5,
        6,
        1,
        2,
    ],
    'monitorChannelsByStationId[130].Key': '386',
    'monitorChannelsByStationId[130].Value': [
        3,
        4,
        5,
        6,
        1,
        2,
    ],
    'monitorChannelsByStationId[131].Key': '387',
    'monitorChannelsByStationId[131].Value': [
        1,
        2,
        3,
        9,
        5,
        4,
    ],
    'monitorChannelsByStationId[132].Key': '391',
    'monitorChannelsByStationId[132].Value': [
        5,
        4,
        1,
        2,
        3,
        9,
    ],
    'monitorChannelsByStationId[133].Key': '393',
    'monitorChannelsByStationId[133].Value': [
        5,
        4,
        1,
        2,
        3,
    ],
    'monitorChannelsByStationId[134].Key': '397',
    'monitorChannelsByStationId[134].Value': [
        10,
        1,
        3,
        2,
        4,
        6,
    ],
    'monitorChannelsByStationId[135].Key': '400',
    'monitorChannelsByStationId[135].Value': [
        1,
        2,
        3,
        4,
        5,
    ],
    'monitorChannelsByStationId[136].Key': '401',
    'monitorChannelsByStationId[136].Value': [
        1,
    ],
    'monitorChannelsByStationId[137].Key': '405',
    'monitorChannelsByStationId[137].Value': [
        3,
        4,
        2,
        5,
    ],
    'monitorChannelsByStationId[138].Key': '406',
    'monitorChannelsByStationId[138].Value': [
        4,
        5,
        3,
        6,
        1,
    ],
    'monitorChannelsByStationId[139].Key': '414',
    'monitorChannelsByStationId[139].Value': [
        4,
        1,
        3,
        2,
        6,
        5,
    ],
    'monitorChannelsByStationId[140].Key': '416',
    'monitorChannelsByStationId[140].Value': [
        1,
        2,
    ],
    'monitorChannelsByStationId[141].Key': '417',
    'monitorChannelsByStationId[141].Value': [
        2,
        4,
        3,
        1,
        5,
        6,
    ],
    'monitorChannelsByStationId[142].Key': '423',
    'monitorChannelsByStationId[142].Value': [
        5,
        7,
        6,
        2,
        8,
    ],
    'monitorChannelsByStationId[143].Key': '426',
    'monitorChannelsByStationId[143].Value': [
        1,
        6,
        2,
        3,
    ],
    'monitorChannelsByStationId[144].Key': '427',
    'monitorChannelsByStationId[144].Value': [
        2,
        1,
        3,
    ],
    'monitorChannelsByStationId[145].Key': '428',
    'monitorChannelsByStationId[145].Value': [
        11,
        2,
        3,
        4,
        10,
        9,
        1,
        6,
        5,
    ],
    'monitorChannelsByStationId[146].Key': '452',
    'monitorChannelsByStationId[146].Value': [
        13,
        2,
        3,
        4,
        12,
        1,
        6,
        5,
    ],
    'monitorChannelsByStationId[147].Key': '453',
    'monitorChannelsByStationId[147].Value': [
        14,
        2,
        3,
        4,
        12,
        11,
        1,
        7,
        6,
        5,
    ],
    'monitorChannelsByStationId[148].Key': '454',
    'monitorChannelsByStationId[148].Value': [
        2,
        3,
        4,
        9,
        20,
        18,
        14,
        8,
        1,
        7,
        6,
        5,
    ],
    'monitorChannelsByStationId[149].Key': '455',
    'monitorChannelsByStationId[149].Value': [
        1,
        11,
        12,
        10,
        13,
    ],
    'monitorChannelsByStationId[150].Key': '456',
    'monitorChannelsByStationId[150].Value': [
        1,
        8,
        9,
        7,
        10,
    ],
    'monitorChannelsByStationId[151].Key': '458',
    'monitorChannelsByStationId[151].Value': [
        10,
        1,
        2,
        3,
        8,
    ],
    'monitorChannelsByStationId[152].Key': '465',
    'monitorChannelsByStationId[152].Value': [
        1,
        5,
        4,
    ],
    'monitorChannelsByStationId[153].Key': '467',
    'monitorChannelsByStationId[153].Value': [
        1,
    ],
    'monitorChannelsByStationId[154].Key': '468',
    'monitorChannelsByStationId[154].Value': [
        3,
        4,
        5,
        1,
        6,
        2,
    ],
    'monitorChannelsByStationId[155].Key': '469',
    'monitorChannelsByStationId[155].Value': [
        3,
        4,
        5,
        1,
        6,
        2,
        8,
        7,
    ],
    'monitorChannelsByStationId[156].Key': '472',
    'monitorChannelsByStationId[156].Value': [
        11,
        2,
        3,
        4,
        10,
        9,
        1,
        6,
        5,
    ],
    'monitorChannelsByStationId[157].Key': '498',
    'monitorChannelsByStationId[157].Value': [
        1,
        7,
        8,
        6,
        9,
    ],
    'monitorChannelsByStationId[158].Key': '499',
    'monitorChannelsByStationId[158].Value': [
        3,
        12,
        13,
        11,
        9,
        18,
        8,
        17,
        1,
        2,
    ],
    'monitorChannelsByStationId[159].Key': '501',
    'monitorChannelsByStationId[159].Value': [
        1,
        2,
        3,
        5,
    ],
    'monitorChannelsByStationId[160].Key': '505',
    'monitorChannelsByStationId[160].Value': [
        6,
    ],
    'monitorChannelsByStationId[161].Key': '509',
    'monitorChannelsByStationId[161].Value': [
        4,
        1,
        2,
        3,
        11,
    ],
    'monitorChannelsByStationId[162].Key': '510',
    'monitorChannelsByStationId[162].Value': [
        1,
        2,
        3,
        7,
        4,
    ],
    'monitorChannelsByStationId[163].Key': '511',
    'monitorChannelsByStationId[163].Value': [
        9,
        2,
        4,
        3,
        1,
        6,
        5,
    ],
    'monitorChannelsByStationId[164].Key': '513',
    'monitorChannelsByStationId[164].Value': [
        4,
        6,
        5,
        2,
        1,
        3,
    ],
    'monitorChannelsByStationId[165].Key': '517',
    'monitorChannelsByStationId[165].Value': [
        1,
    ],
    'monitorChannelsByStationId[166].Key': '528',
    'monitorChannelsByStationId[166].Value': [
        2,
        4,
        3,
        1,
    ],
    'monitorChannelsByStationId[167].Key': '530',
    'monitorChannelsByStationId[167].Value': [
        3,
        1,
        8,
        7,
    ],
    'monitorChannelsByStationId[168].Key': '531',
    'monitorChannelsByStationId[168].Value': [
        1,
        2,
        3,
        4,
        6,
        5,
        9,
        8,
    ],
    'monitorChannelsByStationId[169].Key': '532',
    'monitorChannelsByStationId[169].Value': [
        1,
        2,
        3,
        4,
        6,
        5,
    ],
    'monitorChannelsByStationId[170].Key': '533',
    'monitorChannelsByStationId[170].Value': [
        4,
        1,
        2,
        3,
    ],
    'monitorChannelsByStationId[171].Key': '535',
    'monitorChannelsByStationId[171].Value': [
        2,
        1,
        3,
    ],
    'monitorChannelsByStationId[172].Key': '536',
    'monitorChannelsByStationId[172].Value': [
        1,
    ],
    'monitorChannelsByStationId[173].Key': '537',
    'monitorChannelsByStationId[173].Value': [
        3,
        2,
        1,
        5,
        4,
    ],
    'monitorChannelsByStationId[174].Key': '538',
    'monitorChannelsByStationId[174].Value': [
        3,
        2,
        1,
    ],
    'monitorChannelsByStationId[175].Key': '539',
    'monitorChannelsByStationId[175].Value': [
        7,
        8,
        6,
        5,
        1,
    ],
}


def get_data():
    return requests.post('https://www.svivaaqm.net/report/GetMultiStationReportData', headers=headers, json=json_data).json()
